# Generated by Django 4.1.3 on 2022-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoseikan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='join_date',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
